name: Update devel:languages:perl (Dispatch)
on:
  workflow_dispatch:
    inputs:
      max_modules:
        description: 'Maximum number of perl modules to process'
        required: true
        type: integer
        default: 1
      image:
        description: Image to run on
        type: string
        default: registry.opensuse.org/home/tinita/branches/opensuse/templates/images/tumbleweed/containers/opensuse/example
      repo:
        description: Repo for cpanspec
        type: string
        default: https://github.com/perlpunk/cpanspec
      branch:
        description: cpanspec branch
        type: string
        default: update-perl-gh
      obs_project:
        description: Target project in OBS
        type: string
        default: home:tinita:testautoupdate

jobs:

  update:
    runs-on: ubuntu-latest
    container:
      #image: registry.opensuse.org/opensuse/leap:15.5
      image: ${{ inputs.image }}

    steps:
    - run: |
        zypper in -y git gh
        git config --global --add safe.directory '*'

    - uses: actions/checkout@v4

    - env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh workflow list

    - run: |
        git clone ${{ inputs.repo }}
        cd cpanspec
        git checkout ${{ inputs.branch }}

    - name: fetch cpan releases
      run: |
        pwd
        bin/fetch-cpan.sh
        ls -lrt ~/obs-mirror
        ls -lrt ~/obs-mirror/cpan

    - name: configure osc
      env:
        OSC_USER: ${{ secrets.OSC_USER }}
        OSC_PASSWORD: ${{ secrets.OSC_PASSWORD }}
      run: |
        cp etc/oscrc ~/.oscrc
        perl -pi -wE's/OSC_USER/$ENV{OSC_USER}/' ~/.oscrc
        perl -pi -wE's/OSC_PASSWORD/$ENV{OSC_PASSWORD}/' ~/.oscrc

    - name: status
      run: |
        ./bin/status-perl --data ~/obs-mirror --project ${{ inputs.obs_project }} --update
        grep $'\t''todo' ~/obs-mirror/status/*.tsv || true

    - name: update
      run: |
        ./bin/update-perl \
            --cpanspec "$PWD/cpanspec/cpanspec" \
            --data ~/obs-mirror \
            --project ${{ inputs.obs_project }} \
            --max ${{ inputs.max_modules }} \
            --cpanspec-flags " --dlp"

    - name: ls
      run: |
        ls -lrt ~/obs-mirror
        ls -lrt ~/obs-mirror/cpan

    - uses: actions/upload-artifact@v4
      with:
        name: obs-mirror
        path: |
          ~/obs-mirror/cpan/
          ~/obs-mirror/status/
          ~/obs-mirror/auto.xml
          ~/obs-mirror/perl.xml

# Trigger with gh cli:
# gh workflow run run.yaml --ref workflow -F image=registry.opensuse.org/home/tinita/branches/opensuse/templates/images/tumbleweed/containers/opensuse/example -F repo=https://github.com/perlpunk/cpanspec -F branch=normalize-versions -F obs_project=home:tinita:testautoupdate -F max_modules=1
